services:
  web:
    image: 192.168.0.9:5000/stackdemo
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - com.docker.stack.namespace=FLASK-APP
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8097:8000"